# Generated by Django 5.1.1 on 2024-09-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_nome_material_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='logsAcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=50)),
                ('data_acesso', models.CharField(max_length=50)),
                ('acao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Perfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Saidas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saida_id', models.CharField(max_length=50)),
                ('usuario_id', models.CharField(max_length=50)),
                ('material_id', models.CharField(max_length=50)),
                ('quantidade', models.CharField(max_length=50)),
                ('data_destinacao', models.CharField(max_length=50)),
                ('destinacao', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosPerfis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_id', models.CharField(max_length=50)),
                ('perfil_id', models.CharField(max_length=50)),
            ],
        ),
    ]
